#!/bin/bash
GREEN="\033[92m"
RED="\033[91m"
BLUE="\033[36m"
CLEAR="\033[39m"

if [ -d ".git" ]; then
  git status
  exit $?
fi

folders=($(ls -d */))

max=0
for f in ${folders[@]};do
  if [ ${#f} -gt $max ];then
    max=${#f}
  fi
done
#echo ${folders[@]}
for f in ${folders[@]};do
  if [ ! -d "$f/.git" ]; then
    continue
  fi
  cd $f
  dirt=$(git status --porcelain|wc -l|xargs)
  if [[ $dirt -gt 0 ]]; then
    echo -ne "$RED"
   else
    if [ "$1" = "-f" ];then
      _=$(git fetch &2>1)
    fi
    behind=$(git rev-list HEAD..@{u} | wc -l|xargs)
    ahead=$(git rev-list @{u}..HEAD | wc -l|xargs)
    if [ $behind -eq 0 -a $ahead -eq 0 ]; then
        echo -ne "$GREEN"
    elif [ $behind -gt 0 -a $ahead -gt 0 ]; then
      echo -ne "$RED"
    elif [ $behind -gt 0 ]; then
        echo -ne "$BLUE"
    else
        echo -ne "$BLUE"
    fi
  fi
  echo -ne $f
  for i in `seq ${#f} $max`;do
    echo -n " "
  done
  echo -ne "$CLEAR\t"
  cd ..
done
echo ""
